### PR TITLE
Oracle Heroku Buildpack

### PR DESCRIPTION
**Pull request by karneyli**

### CODE REVIEW

**Comment by bretthuneycutt** [comment]
interesting!

**Comment by bretthuneycutt** [comment]
am i the right person to review this?

**Comment by karneyli** [comment]
yes... to say the least, I learned a _lot_ about Heroku this weekend.

On Mon, Aug 24, 2015 at 10:29 AM, Brett Huneycutt <notifications@github.com>
wrote:

> interesting!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wealthsimple/oracle-heroku-buildpack/pull/3#issuecomment-134226515>
> .
>



-- 
Karney Li
Software Engineering - WealthSimple | Smart Investing
<http://www.wealthsimple.com>

**Comment by bretthuneycutt** [comment]
:shipit:

**Pull request merged**
